version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@6"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: make ci-docker-build
      - save_cache:
          key: build-artifact-{{ .Branch }}-{{ .Revision }}
          paths:
            - "build"

workflows:
  build:
    jobs:
      - build:
          context: billing
